//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public AccessLog()
        {
            this.LogEntryProcessed = false;
            this.Hardware = new HashSet<Hardware>();
        }
    
        public long Id { get; set; }
        public AccessLogAccessType AccessType { get; set; }
        public System.DateTime AccessDateTime { get; set; }
        public bool LogEntryProcessed { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual PC PC { get; set; }
        public virtual DocumentPath DocumentPath { get; set; }
        public virtual UserAccess UserAccess { get; set; }
        public virtual ICollection<Hardware> Hardware { get; set; }
    }
}
