//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public Administrator()
        {
            this.Login = "\"\"";
            this.Password = "\"\"";
            this.NeedsToChangePassword = false;
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool NeedsToChangePassword { get; set; }
    }
}
