//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersionChange
    {
        public DocumentVersionChange()
        {
            this.Version = 0;
            this.DocumentPart = "\"\"";
        }
    
        public long Id { get; set; }
        public long Version { get; set; }
        public string DocumentPart { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
