//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Version = 0;
            this.DocumentPart = "\"\"";
            this.UserAccess = new HashSet<UserAccess>();
            this.DocumentPath = new HashSet<DocumentPath>();
            this.AccessLog = new HashSet<AccessLog>();
            this.DocumentVersionChange = new HashSet<DocumentVersionChange>();
        }
    
        public long Id { get; set; }
        public System.Guid DocumentID { get; set; }
        public System.DateTime LastChange { get; set; }
        public long Version { get; set; }
        public string DocumentPart { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual ICollection<UserAccess> UserAccess { get; set; }
        public virtual User LastUserAccess { get; set; }
        public virtual User LastUserAccessWithChanges { get; set; }
        public virtual ICollection<DocumentPath> DocumentPath { get; set; }
        public virtual ICollection<AccessLog> AccessLog { get; set; }
        public virtual ICollection<DocumentVersionChange> DocumentVersionChange { get; set; }
    }
}
