//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentID = "\"\"";
            this.Version = 0;
            this.UserAccess = new HashSet<UserAccess>();
            this.DocumentPath = new HashSet<DocumentPath>();
            this.AccessLog = new HashSet<AccessLog>();
        }
    
        public int Id { get; set; }
        public string DocumentID { get; set; }
        public System.DateTime LastChange { get; set; }
        public long Version { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual ICollection<UserAccess> UserAccess { get; set; }
        public virtual User LastUserAccess { get; set; }
        public virtual User LastUserAccessWithChanges { get; set; }
        public virtual ICollection<DocumentPath> DocumentPath { get; set; }
        public virtual ICollection<AccessLog> AccessLog { get; set; }
    }
}
