//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class DRDLPModelContainer : DbContext
    {
        public DRDLPModelContainer()
            : base("name=DRDLPModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrator> AdministratorSet { get; set; }
        public DbSet<Hardware> HardwareSet { get; set; }
        public DbSet<PC> PCSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Document> DocumentSet { get; set; }
        public DbSet<UserAccess> UserAccessSet { get; set; }
        public DbSet<DocumentPath> DocumentPathSet { get; set; }
        public DbSet<AccessLog> AccessLogSet { get; set; }
        public DbSet<DocumentVersionChange> DocumentVersionChangeSet { get; set; }
    }
}
