//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    
    public enum HardwareTypeEnum : byte
    {
        CPU = 0,
        MB = 1,
        VGA = 2,
        USB = 3,
        OTHER = 4
    }
}
