//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public PC()
        {
            this.Valid = true;
            this.PCHardwareBasedID = "\"\"";
            this.Name = "\"\"";
            this.Hardware = new HashSet<Hardware>();
            this.Users = new HashSet<User>();
            this.Documents = new HashSet<Document>();
            this.DocumentPath = new HashSet<DocumentPath>();
            this.AccessLog = new HashSet<AccessLog>();
        }
    
        public int Id { get; set; }
        public bool Valid { get; set; }
        public string PCHardwareBasedID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Hardware> Hardware { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<DocumentPath> DocumentPath { get; set; }
        public virtual ICollection<AccessLog> AccessLog { get; set; }
    }
}
