//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Login = "\"\"";
            this.Valid = true;
            this.UserAccesses = new HashSet<UserAccess>();
            this.AccessLog = new HashSet<AccessLog>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public bool Valid { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual ICollection<UserAccess> UserAccesses { get; set; }
        public virtual Document LastAccessDocuments { get; set; }
        public virtual Document LastChangedDocuments { get; set; }
        public virtual ICollection<AccessLog> AccessLog { get; set; }
    }
}
