//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    
    public enum UserAccessAccessTypeEnum : byte
    {
        FullAccess = 0,
        ReadOnly = 1,
        AccessDenied = 2
    }
}
