//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRDLPSystemDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public UserAccess()
        {
            this.Users = new HashSet<User>();
            this.AccessLog = new HashSet<AccessLog>();
        }
    
        public UserAccessAccessTypeEnum AccessType { get; set; }
    
        public virtual Document Documents { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<AccessLog> AccessLog { get; set; }
    }
}
